apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: next-terminal
  name: next-terminal
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: next-terminal
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: next-terminal
    spec:
      containers:
        - env:
            - name: DB
              value: mysql
            - name: GUACD_HOSTNAME
              value: guacd
            - name: GUACD_PORT
              value: "4822"
            - name: MYSQL_DATABASE
              value: next-terminal
            - name: MYSQL_HOSTNAME
              value: mysql
            - name: MYSQL_PASSWORD
              value: next-terminal
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              value: next-terminal
          image: dushixiang/next-terminal:latest
          name: next-terminal
          ports:
            - containerPort: 8088
          resources: {}
          volumeMounts:
            - mountPath: /etc
              name: next-terminal-claim0
            - mountPath: /usr/local/next-terminal/data
              name: next-terminal-claim1
      restartPolicy: Always
      volumes:
        - name: next-terminal-claim0
          persistentVolumeClaim:
            claimName: next-terminal-claim0
        - name: next-terminal-claim1
          persistentVolumeClaim:
            claimName: next-terminal-claim1
status: {}
