kubectl apply -f mysql-claim0-persistentvolumeclaim.yaml -n next-terminal
kubectl apply -f mysql-deployment.yaml  -n next-terminal
kubectl apply -f mysql-service.yaml -n next-terminal
kubectl apply -f guacd-claim0-persistentvolumeclaim.yaml -n next-terminal
kubectl apply -f guacd-deployment.yaml -n next-terminal
kubectl apply -f guacd-service.yaml -n next-terminal
kubectl apply -f next-terminal-claim0-persistentvolumeclaim.yaml -n next-terminal
kubectl apply -f next-terminal-claim1-persistentvolumeclaim.yaml -n next-terminal
kubectl apply -f next-terminal-deployment.yaml -n next-terminal
kubectl apply -f next-terminal-service.yaml -n next-terminal
