export const ACCESS_HEADER_HEIGHT = 40;
export const ACCESS_SIDEBAR_DEFAULT_SIZE = 15;
export const ACCESS_SIDEBAR_MAX_SIZE = 20;
export const ACCESS_SIDEBAR_COLLAPSED_SIZE = 0;
export const ACCESS_SIDEBAR_EXPANDED_MIN_WIDTH = 240;
export const ACCESS_SIDEBAR_COLLAPSED_MIN_WIDTH = 0;
